site_name: Intern at Client Ascension
theme:
  name: material
  palette:
    - scheme: default
      primary: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
nav:
  - Home: index.md
  - Glossary: glossary.md
  - Offers: offers.md
  - Funnel: funnel.md
  - Cold Email: cold_email.md
  - Sales: sales.md
  - Fulfillment: fulfillment.md
  - Hiring: hiring.md
  - Personal Brand: personal_brand.md

plugins:
  - glightbox
  - search
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences